### ISSUE TITLE
Mock unavailable libraries?

### ISSUE THREAD

**Issue by AchimKern** [daizutabi/mkapi#11]
Hi ,

I would like do to document a project that makes heavy use of external libraries where I don't have access to the sources. Does mkapi offer something similar to mocks in sphinxs/autodoc
autodoc_mock_imports = ["django","td"]?

Thanks in advance

**Comment by AchimKern** [comment]
in other words, is there a way to configure/run something like this when documentation is created
``` python
import sys
from unittest.mock import MagicMock as mock
sys.modules["td"] = mock()
```

**Comment by daizutabi** [comment]
In Version 0.8.1, `on_config` option was added. See [this example](https://mkapi.daizutabi.net/usage/custom/)

In your case, please try:

```python
# setup.py
import sys
from unittest.mock import MagicMock as mock

def on_config():
    sys.modules["td"] = mock()
```

and

```yaml
# mkdocs.yml
plugins:
  - mkapi:
    src_dirs: [<path_to_setup.py>]
    on_config: setup.config
```
