### ISSUE TITLE
Code block formatted incorrectly

### ISSUE THREAD

**Issue by twsl** [daizutabi/mkapi#123]
Using the latest version of both `mkapi` and the `mkdocs-material` theme, the api code is formatted incorrectly.
This issue has been introduced by https://github.com/squidfunk/mkdocs-material/commit/4eb1a4393741b1ecf8019dd53292b7a4d02e16f5

I bypassed this for now by overwriting it:
```css
.md-typeset .md-code__content {
    display: block !important;
}
```
But I assume this is not the proper solution and might need investigation.
