### ISSUE TITLE
Bug: Namespace packages do not work with page mode

### ISSUE THREAD

**Issue by mcarans** [daizutabi/mkapi#219]
@daizutabi Thanks for what is a very useful project that should allow me to replace the no longer developed pydoc-markdown.

I have been trying to get generation to work with namespace packages and page mode.

I have a structure src/hdx/utilities/ with various source files in there. With no `__init__.py` in the hdx folder when I run `mkdocs build`, no api or src folders are generated in the site dir. As soon as I add an empty `__init__.py` and run mkdocs, then api and src folders are created. The lack of any error message on failure is very confusing. 

It seems that namespace packages are not supported in page mode although I note an [old issue](https://github.com/daizutabi/mkapi/issues/30) which presumably fixed it for object mode. Please can you fix it for page mode.

Additionally, in order to get it to work I have to run `export PYTHONPATH=./src` before running `mkdocs build`. Is there any way to avoid that step?

**Comment by daizutabi** [comment]
Can you share the `nav` configuration from your `mkdocs.yml`?

**Comment by mcarans** [comment]
@daizutabi I have made a test repo here: https://github.com/mcarans/mkdocs-test
It produces output with `mkdocs build -f documentation/mkdocs.yaml`

If you delete src/hdx/__init__.py it no longer produces the api folder under site.

**Comment by daizutabi** [comment]
daizutabi/astdoc#11

**Comment by daizutabi** [comment]
Fixed in version 4.1.1

To avoid `export PYTHONPATH=./src`, install your project in virtual environment (mcarans/mkdocs-test#1)

**Comment by mcarans** [comment]
Brilliant, thx @daizutabi . I added an optional dependency:
```
docs = ["mkapi"]
```

Then my readthedocs.yaml is:
```
# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - pip install .[docs]

mkdocs:
  configuration: documentation/mkdocs.yaml
```
