### ISSUE TITLE
Instructions only generate API for "mkapi"?

### ISSUE THREAD

**Issue by tony** [daizutabi/mkapi#22]
(Edit: Found a bug, will make a PR)

I couldn't find instructions on how set the package (sorry if I'm missing something). I am only able to generate `mkdocs` itself.

```
Name: mkapi
Version: 1.0.12
Summary: An Auto API Documentation tool.
Home-page: https://mkapi.daizutabi.net
Author: daizutabi
Author-email: daizutabi@gmail.com
License: MIT
Location: /home/t/work/python/libvcs/.venv/lib/python3.7/site-packages
Requires: jinja2, markdown
Required-by:
```

```
libvcs on  new-docs [✘!] ❯ python -V
Python 3.7.7
libvcs on  new-docs [✘!] ❯ pip show mkdocs
Name: mkdocs
Version: 1.1.2
Summary: Project documentation with Markdown.
Home-page: https://www.mkdocs.org
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: /home/t/work/python/libvcs/.venv/lib/python3.7/site-packages
Requires: PyYAML, Jinja2, tornado, livereload, lunr, click, Markdown
Required-by: mkdocstrings, mkdocs-material
```
![image](https://user-images.githubusercontent.com/26336/89126811-6f9a4280-d4ae-11ea-9b4f-242bb4de31b9.png)

mkdocs.yml:

```yaml
# mkdocs.yml
site_name: libvcs
site_url: https://libvcs.git-pull.com
repo_url: https://github.com/vcs-python/libvcs
repo_name: 'GitHub'
theme:
  name: "material"
  custom_dir: .
  logo: assets/images/libvcs.svg
  favicon: assets/images/favicon.ico

plugins:
  - search
  - mkapi

nav:
  - index.md
  - API: mkapi/api/mkapi
  #   - API: mkapi/api/libvcs will crash
```
