### ISSUE TITLE
Is it possible to obtain generated markdown files of the docstrings from mkapi?

### ISSUE THREAD

**Issue by mcarans** [daizutabi/mkapi#233]
My organisation is considering using GitBook. It looks like that tool needs markdown input. Is it possible to obtain markdown file output from mkapi that is generated from the docstrings?

**Comment by lmuenter** [comment]
I have to second this question. For a multi-repo docs service, we also require rendered markdown. Is it possible to obtain the generated markdown?

**Comment by daizutabi** [comment]
@mcarans @lmuenter I've added a `save` option in version 4.4.1 that will save the markdown files of API pages to the `docs_dir`.

Usage:

```yaml
plugins:
  - mkapi:
      save: true  # Save markdown files
```

When this option is enabled:
- Markdown files for API pages will be saved to `docs_dir`
- Files will be saved in the corresponding paths within `docs_dir`

Note: The saved markdown files contain HTML elements (like `<div>` tags and Font Awesome icons) that are specific to MkDocs. When these files are used with GitBook or other tools, you may need to modify the HTML elements to match your target documentation system's requirements.

**Comment by daizutabi** [comment]
@mcarans I've enhanced the `save` option in version 4.4.2 to accept both boolean and string values. Now you can specify a custom directory for saving the markdown files:

```yaml
plugins:
  - mkapi:
      save: "output/markdown"  # Save to custom directory relative to the current directory
```

When `save` is a string, files will be saved to the specified directory (relative to the current directory) instead of `docs_dir`.

The existing boolean behavior remains unchanged:

```yaml
plugins:
  - mkapi:
      save: true  # Save to docs_dir (existing behavior)
```
